/* confdefs.h */
#define PACKAGE_NAME "Gridlab-D"
#define PACKAGE_TARNAME "gridlabd"
#define PACKAGE_VERSION "2.2.0.3223M"
#define PACKAGE_STRING "Gridlab-D 2.2.0.3223M"
#define PACKAGE_BUGREPORT "David Chassin <david.chassin@pnl.gov>"
#define PACKAGE_URL ""
#define PACKAGE "gridlabd"
#define VERSION "2.2.0.3223M"
#define REALTIME_LDFLAGS "-export-all-symbols"
#define DLEXT ".so"
#define STDC_HEADERS 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_MEMORY_H 1
#define HAVE_STRINGS_H 1
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_UNISTD_H 1
#define HAVE_DLFCN_H 1
#define LT_OBJDIR ".libs/"
#define HAVE_PTHREAD 1
#define HAVE___SYNC_BOOL_COMPARE_AND_SWAP 1
#define HAVE___SYNC_ADD_AND_FETCH 1
#define STDC_HEADERS 1
#define HAVE_MALLOC_H 1
#define HAVE_MEMORY_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_UNISTD_H 1
#define HAVE__BOOL 1
#define HAVE_STDBOOL_H 1
#define HAVE_STDLIB_H 1
#define HAVE_MALLOC 1
#define TIME_WITH_SYS_TIME 1
#define HAVE_SYS_TIME_H 1
#define HAVE_UNISTD_H 1
#define HAVE_ALARM 1
#define HAVE_STDLIB_H 1
#define HAVE_REALLOC 1
#define HAVE_STRFTIME 1
#define HAVE_VPRINTF 1
#define HAVE_ATEXIT 1
#define HAVE_GETCWD 1
#define HAVE_MEMSET 1
#define HAVE_PUTENV 1
#define HAVE_STRCHR 1
#define HAVE_STRERROR 1
#define HAVE_STRRCHR 1
#define HAVE_TZSET 1
#define HAVE_PTHREAD 1
#define HAVE_GET_NPROCS 1
